version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: presencetracker
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
  web:
    build: .
    volumes:
      - .:/app
      - media_data:/app/media
      - static_data:/app/staticfiles
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://user:password@db/presencetracker
      DEBUG: "True"
      DJANGO_SECRET_KEY: django-insecure-%#en!j)rk9f(^w=_t*-pw0wht-t7d-(9+uy-n!=p*us3z0*-fs
      DJANGO_ALLOWED_HOSTS: "*"
      CORS_ALLOW_ALL_ORIGINS: "True"
      CORS_ALLOWED_ORIGINS: "*"

volumes:
  postgres_data:
  media_data:
  static_data:
